# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Veracode Upload And Scan
        uses: veracode/veracode-uploadandscan-action@0.2.1
        with:
          # appname
          appname: veracode Level 3
          # createprofile
          createprofile: true
          # filepath
          filepath: ./target/verademo.war
          # version
          version: ${{ github.run_id }}
          # vid
          vid: ${{secrets.VERACODE_API_ID}}
          # vkey
          vkey: ${{secrets.VERACODE_API_KEY}}
          # wait X minutes for the scan to complete
          #scantimeout: 0
          # business criticality - policy selection
          criticality: High
          # selected modules like from previous scan
          selectedpreviously: true
          createsandbox: true
          sandboxname: 'Level 3'
      - name: Invoke deployment hook
        uses: distributhor/workflow-webhook@v1
        env:
          webhook_type: 'json-extended'
          webhook_url: 'https://3hw3qhllv7.execute-api.ap-southeast-2.amazonaws.com/prod/github'
          webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
          data: '{"commit": "${{github.sha}}","run_id":"${{github.run_id}}", "veracode_app_name":"veracode-async","veracode_sandbox_name":"lets see if it works 2"}' 
          #,"veracode_sandbox_name":"lets see if it works 3"}'
         
